# -*- coding: utf-8 -*-
"""
/***************************************************************************
 solemap_tool
                                 A QGIS plugin
 solemap_tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-24
        copyright            : (C) 2024 by masco
        email                : sscc1234@naver.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load solemap_tool class from file solemap_tool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .solemap_tool import solemap_tool
    return solemap_tool(iface)
